# Generated by Django 3.2.6 on 2021-08-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('email', models.TextField(verbose_name='E-mail')),
                ('assunto', models.TextField(verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Imagem')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.TextField(verbose_name='Categoria')),
            ],
        ),
    ]
